<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\HomeFeedController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\RegionController;
use App\Http\Controllers\Api\SearchController;
use App\Http\Controllers\Api\FilterController;
use App\Http\Controllers\Api\CompanyController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductShowController;
use App\Http\Controllers\Api\ProductSimilarController;
use App\Http\Controllers\Api\FavoriteController;
use App\Http\Controllers\Api\SavedSearchController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\BidController;
use App\Http\Controllers\Api\CommentController;
use App\Http\Controllers\Api\UploadController;
use App\Http\Controllers\Api\Admin\AdminCategoryController;
use App\Http\Controllers\Api\Admin\AdminUserController;
use App\Http\Controllers\Api\Admin\AdminAnalyticsController;
use App\Http\Controllers\Api\Admin\AdminAuditController;
use App\Http\Controllers\Api\Admin\AdminProductController;
use App\Http\Controllers\Api\Admin\AdminRegionController;
use App\Http\Controllers\Api\Admin\AdminPermissionController;
use App\Http\Controllers\Api\Admin\AdminTaskController;
use App\Http\Controllers\Api\Admin\AdminOverviewController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\PurchaseController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\MyListingsController;
use App\Http\Controllers\Api\Admin\AdminVerificationController;
use App\Http\Controllers\Api\Admin\AdminOrderController;
use App\Http\Controllers\Api\Admin\AdminContactInquiryController;
use App\Http\Controllers\Api\ContactController;
use App\Http\Controllers\Api\AnnouncementController;
use App\Http\Controllers\Api\Admin\AdminAnnouncementController;
use App\Http\Controllers\Api\Admin\AdminMessageController;
use App\Http\Controllers\Api\Admin\AdminVisitorController;
use App\Http\Controllers\Api\PublicProfileController;

Route::prefix('v1')->group(function () {
    // Public
    Route::get('/homepage/feed', HomeFeedController::class);
    Route::get('/homepage/features', \App\Http\Controllers\Api\HomepageFeaturesController::class);
    Route::get('/categories', [CategoryController::class, 'index']);
    Route::get('/categories/{category}/subcategories', [CategoryController::class, 'subcategories']);
    Route::get('/regions', [RegionController::class, 'index']);
    Route::get('/areas', [RegionController::class, 'index']);
    Route::get('/regions/{region}/cities', [RegionController::class, 'cities']);
    Route::get('/companies', [CompanyController::class, 'index']);
    Route::get('/search', SearchController::class);
    Route::get('/filters', FilterController::class);
        Route::get('/products/{product}', ProductShowController::class);
        Route::post('/products/{product}/view', \App\Http\Controllers\Api\ProductViewController::class);
        Route::get('/products/{product}/similar', ProductSimilarController::class);
    Route::post('/contact', [ContactController::class, 'store']);
    Route::get('/announcements', [AnnouncementController::class, 'index']);
    Route::post('/visitors/track', [\App\Http\Controllers\Api\VisitorController::class, 'track']);
    Route::get('/products/{product}/comments', [CommentController::class, 'index']);
    Route::get('/users/by-username/{username}', [ProfileController::class, 'showByUsername']);
    Route::get('/users/{user}', [ProfileController::class, 'show']);
    Route::get('/profile/by-id/{id}', [PublicProfileController::class, 'showById']);
    Route::get('/profile/by-id/{id}/listings', [PublicProfileController::class, 'listingsById']);
    Route::get('/profile/by-id/{id}/reviews', [PublicProfileController::class, 'reviewsById']);
    Route::get('/profile/{username}', [PublicProfileController::class, 'show']);
    Route::get('/profile/{username}/listings', [PublicProfileController::class, 'listings']);
    Route::get('/profile/{username}/reviews', [PublicProfileController::class, 'reviews']);

    // Auth (public)
    Route::post('/auth/register', [AuthController::class, 'register']);
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::post('/auth/verify-email', [AuthController::class, 'verifyEmail']);
    Route::post('/auth/confirm-email', [AuthController::class, 'confirmEmail']);
    Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);

    // Auth (protected)
    Route::middleware('auth.api')->group(function () {
        Route::post('/upload', [UploadController::class, 'store']);
        Route::post('/auth/register/company', [AuthController::class, 'registerCompany']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/auth/user', [AuthController::class, 'user']);
        Route::post('/auth/change-password', [AuthController::class, 'changePassword']);
        Route::middleware('can.create.listing')->group(function () {
            Route::post('/products', [ProductController::class, 'store']);
            Route::put('/products/{product}', [ProductController::class, 'update']);
            Route::post('/products/{product}/publish', [ProductController::class, 'publish']);
        });
        Route::get('/products', [ProductController::class, 'index']);
        Route::get('/favorites', [FavoriteController::class, 'index']);
        Route::post('/favorites/{product}', [FavoriteController::class, 'store']);
        Route::delete('/favorites/{product}', [FavoriteController::class, 'destroy']);
        Route::get('/saved-searches', [SavedSearchController::class, 'index']);
        Route::post('/saved-searches', [SavedSearchController::class, 'store']);
        Route::delete('/saved-searches/{savedSearch}', [SavedSearchController::class, 'destroy']);
        Route::get('/conversations', [MessageController::class, 'index']);
        Route::get('/conversations/{conversation}', [MessageController::class, 'show']);
        Route::post('/messages', [MessageController::class, 'store']);
        Route::post('/conversations/{conversation}/messages', [MessageController::class, 'reply']);
        Route::get('/products/{product}/bids', [BidController::class, 'index']);
        Route::post('/products/{product}/bids', [BidController::class, 'store']);
        Route::post('/products/{product}/bids/{bid}/accept', \App\Http\Controllers\Api\BidAcceptController::class);
        Route::post('/products/{product}/bids/{bid}/reject', [BidController::class, 'reject']);
        Route::delete('/products/{product}/bids/{bid}', [BidController::class, 'destroy']);
        Route::patch('/products/{product}/bids/{bid}/visibility', [BidController::class, 'toggleVisibility']);
        Route::post('/products/{product}/view-request', \App\Http\Controllers\Api\ViewRequestController::class);
        Route::post('/products/{product}/comments', [CommentController::class, 'store']);
        // Legacy route (kept): like/dislike
        Route::post('/products/{product}/comments/{comment}/like', \App\Http\Controllers\Api\CommentLikeController::class);
        // Spec routes
        Route::put('/comments/{comment}', [CommentController::class, 'update']);
        Route::patch('/comments/{comment}/visibility', [CommentController::class, 'toggleVisibility']);
        Route::post('/comments/{comment}/like', \App\Http\Controllers\Api\CommentLikeController::class);
        Route::delete('/comments/{comment}', [CommentController::class, 'destroy']);
        Route::post('/products/{product}/bump', [ProductController::class, 'bump']);
        Route::delete('/products/{product}', [ProductController::class, 'destroy']);
        Route::post('/products/{product}/purchase', [PurchaseController::class, 'store']);
        Route::get('/notifications', [NotificationController::class, 'index']);
        Route::post('/notifications/{notification}/read', [NotificationController::class, 'markAsRead']);
        Route::post('/notifications/read-all', [NotificationController::class, 'markAllAsRead']);
        Route::put('/profile', [ProfileController::class, 'update']);
        Route::post('/profile/avatar', [ProfileController::class, 'updateAvatar']);
        Route::post('/profile/cover', [ProfileController::class, 'updateCover']);
        Route::get('/users/{user}/reviews', [ReviewController::class, 'index']);
        Route::post('/reviews', [ReviewController::class, 'store']);
        Route::put('/reviews/{review}', [ReviewController::class, 'update']);
        Route::delete('/reviews/{review}', [ReviewController::class, 'destroy']);
        Route::get('/reviews/my', [ReviewController::class, 'myReviews']);
        Route::get('/reviews/given', [ReviewController::class, 'reviewsGiven']);

        // Account: verification, guarantee, balance, orders
        Route::post('/account/verify-document', [AccountController::class, 'verifyDocument']);
        Route::get('/account/verification-status', [AccountController::class, 'verificationStatus']);
        Route::post('/account/verify-absher', [AccountController::class, 'verifyAbsher']);
        Route::post('/account/deposit-guarantee', [AccountController::class, 'depositGuarantee']);
        Route::post('/account/refund-guarantee', [AccountController::class, 'refundGuarantee']);
        Route::get('/account/guarantee-status', [AccountController::class, 'guaranteeStatus']);
        Route::get('/account/listings', [ProductController::class, 'index']);
        Route::get('/account/balance', [AccountController::class, 'balance']);
        Route::get('/account/transactions', [AccountController::class, 'transactions']);
        Route::get('/account/reports', [AccountController::class, 'reports']);
        Route::post('/account/balance/charge', [AccountController::class, 'charge']);
        Route::post('/account/confirm-receipt', [AccountController::class, 'confirmReceipt']);
        Route::post('/account/withdraw', [AccountController::class, 'withdraw']);
        Route::get('/account/stats', [AccountController::class, 'stats']);
        Route::get('/dashboard/home', [AccountController::class, 'dashboardHome']);
        Route::prefix('dashboard/listings')->group(function () {
            Route::get('/', [MyListingsController::class, 'index']);
            Route::patch('/{product}/status', [MyListingsController::class, 'toggleStatus']);
            Route::post('/{product}/bump', [MyListingsController::class, 'bump']);
            Route::delete('/{product}', [MyListingsController::class, 'destroy']);
            Route::patch('/{product}/mark-sold', [MyListingsController::class, 'markSold']);
            Route::post('/{product}/duplicate', [MyListingsController::class, 'duplicate']);
        });
        Route::get('/account/visitor-stats', [AccountController::class, 'visitorStats']);
        Route::post('/account/verify-company', [AccountController::class, 'verifyCompany']);
        Route::get('/account/orders', [OrderController::class, 'index']);
        Route::get('/account/orders/{order}', [OrderController::class, 'show']);
        Route::put('/account/orders/{order}', [OrderController::class, 'update']);
        Route::put('/account/orders/{order}/confirm', [OrderController::class, 'confirm']);
        Route::put('/account/orders/{order}/cancel', [OrderController::class, 'cancel']);
        Route::put('/account/orders/{order}/dispute', [OrderController::class, 'dispute']);
    });

    // Admin (protected, role: super_admin, admin, manager)
    Route::middleware(['auth.api', 'role:super_admin,admin,manager,employee'])->prefix('admin')->group(function () {
        Route::post('/comments/{comment}/reply', [CommentController::class, 'teamReply']);
        Route::get('/categories', [AdminCategoryController::class, 'index']);
        Route::post('/categories', [AdminCategoryController::class, 'store']);
        Route::put('/categories/{category}', [AdminCategoryController::class, 'update']);
        Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy']);
        Route::post('/categories/bulk-update', [AdminCategoryController::class, 'bulkUpdate']);
        Route::post('/categories/bulk-destroy', [AdminCategoryController::class, 'bulkDestroy']);
        Route::post('/categories/{category}/subcategories', [AdminCategoryController::class, 'storeSubcategory']);
        Route::put('/categories/{category}/subcategories/{subcategory}', [AdminCategoryController::class, 'updateSubcategory']);
        Route::delete('/categories/{category}/subcategories/{subcategory}', [AdminCategoryController::class, 'destroySubcategory']);
        Route::post('/categories/{category}/regions/{region}/toggle', [AdminCategoryController::class, 'toggleRegion']);
        Route::post('/categories/{category}/regions/{region}/wholesale', [AdminCategoryController::class, 'toggleWholesale']);
        Route::get('/orders', [AdminOrderController::class, 'index']);
        Route::get('/orders/{purchase}', [AdminOrderController::class, 'show']);
        Route::put('/orders/{purchase}', [AdminOrderController::class, 'update']);
        Route::get('/users', [AdminUserController::class, 'index']);
        Route::get('/users/{user}', [AdminUserController::class, 'show']);
        Route::put('/users/{user}', [AdminUserController::class, 'update']);
        Route::get('/products', [AdminProductController::class, 'index']);
        Route::get('/products/{product}', [AdminProductController::class, 'show']);
        Route::put('/products/{product}', [AdminProductController::class, 'update']);
        Route::delete('/products/{product}', [AdminProductController::class, 'destroy']);
        Route::get('/regions', [AdminRegionController::class, 'index']);
        Route::post('/regions', [AdminRegionController::class, 'store']);
        Route::put('/regions/{region}', [AdminRegionController::class, 'update']);
        Route::delete('/regions/{region}', [AdminRegionController::class, 'destroy']);
        Route::post('/regions/bulk-update', [AdminRegionController::class, 'bulkUpdate']);
        Route::post('/regions/bulk-destroy', [AdminRegionController::class, 'bulkDestroy']);
        Route::post('/regions/{region}/cities', [AdminRegionController::class, 'storeCity']);
        Route::put('/regions/{region}/cities/{city}', [AdminRegionController::class, 'updateCity']);
        Route::delete('/regions/{region}/cities/{city}', [AdminRegionController::class, 'destroyCity']);
        Route::get('/permissions', [AdminPermissionController::class, 'index']);
        Route::get('/permissions/roles', [AdminPermissionController::class, 'roles']);
        Route::get('/permissions/roles/{role}', [AdminPermissionController::class, 'rolePermissions']);
        Route::put('/permissions/roles/{role}', [AdminPermissionController::class, 'syncRole']);
        Route::get('/tasks', [AdminTaskController::class, 'index']);
        Route::post('/tasks', [AdminTaskController::class, 'store']);
        Route::put('/tasks/{task}', [AdminTaskController::class, 'update']);
        Route::delete('/tasks/{task}', [AdminTaskController::class, 'destroy']);
        Route::get('/tasks/assignees', [AdminTaskController::class, 'assignees']);
        Route::get('/contact-inquiries', [AdminContactInquiryController::class, 'index']);
        Route::get('/contact-inquiries/assignees', [AdminContactInquiryController::class, 'assignees']);
        Route::get('/contact-inquiries/{contact_inquiry}', [AdminContactInquiryController::class, 'show']);
        Route::put('/contact-inquiries/{contact_inquiry}', [AdminContactInquiryController::class, 'update']);
        Route::get('/announcements', [AdminAnnouncementController::class, 'index']);
        Route::post('/announcements', [AdminAnnouncementController::class, 'store']);
        Route::put('/announcements/{admin_announcement}', [AdminAnnouncementController::class, 'update']);
        Route::delete('/announcements/{admin_announcement}', [AdminAnnouncementController::class, 'destroy']);
        Route::get('/conversations', [AdminMessageController::class, 'index']);
        Route::get('/conversations/{conversation}', [AdminMessageController::class, 'show']);
        Route::get('/visitors', [AdminVisitorController::class, 'index']);
        Route::post('/users/{user}/ban', [AdminUserController::class, 'ban']);
        Route::post('/users/{user}/unban', [AdminUserController::class, 'unban']);
        Route::post('/users/{user}/suspend', [AdminUserController::class, 'suspend']);
        Route::post('/users/{user}/unsuspend', [AdminUserController::class, 'unsuspend']);
        Route::post('/users/{user}/verify', [AdminUserController::class, 'verify']);
        Route::post('/users/{user}/refund-guarantee', [AdminUserController::class, 'refundGuarantee']);
        Route::post('/products/{product}/approve', [AdminProductController::class, 'approve']);
        Route::post('/products/{product}/reject', [AdminProductController::class, 'reject']);
        Route::get('/analytics', AdminAnalyticsController::class);
        Route::get('/analytics/regions', [AdminAnalyticsController::class, 'regions']);
        Route::get('/overview', AdminOverviewController::class);
        Route::get('/audit-logs', [AdminAuditController::class, 'index']);
        Route::get('/verifications', [AdminVerificationController::class, 'index']);
        Route::post('/verifications/{document_verification}/approve', [AdminVerificationController::class, 'approve']);
        Route::post('/verifications/{document_verification}/reject', [AdminVerificationController::class, 'reject']);
    });
});
