<?php

use App\Http\Controllers\Api\AccountController;
use App\Http\Controllers\Api\Admin\AdminAnalyticsController;
use App\Http\Controllers\Api\Admin\AdminAnnouncementController;
use App\Http\Controllers\Api\Admin\AdminAuditController;
use App\Http\Controllers\Api\Admin\AdminBidController;
use App\Http\Controllers\Api\Admin\AdminCategoryController;
use App\Http\Controllers\Api\Admin\AdminChargeRequestController;
use App\Http\Controllers\Api\Admin\AdminCompanyVerificationController;
use App\Http\Controllers\Api\Admin\AdminContactInquiryController;
use App\Http\Controllers\Api\Admin\AdminGuaranteeRequestController;
use App\Http\Controllers\Api\Admin\AdminListingReportController;
use App\Http\Controllers\Api\Admin\AdminMessageController;
use App\Http\Controllers\Api\Admin\AdminOrderController;
use App\Http\Controllers\Api\Admin\AdminOverviewController;
use App\Http\Controllers\Api\Admin\AdminPermissionController;
use App\Http\Controllers\Api\Admin\AdminProductController;
use App\Http\Controllers\Api\Admin\AdminProfileReportController;
use App\Http\Controllers\Api\Admin\AdminRegionController;
use App\Http\Controllers\Api\Admin\AdminSecuritySettingsController;
use App\Http\Controllers\Api\Admin\AdminBrandingController;
use App\Http\Controllers\Api\Admin\AdminSettingsController;
use App\Http\Controllers\Api\BrandingController;
use App\Http\Controllers\Api\Admin\AdminTaskController;
use App\Http\Controllers\Api\Admin\AdminUserController;
use App\Http\Controllers\Api\Admin\AdminVerificationController;
use App\Http\Controllers\Api\Admin\AdminVisitorController;
use App\Http\Controllers\Api\Admin\AdminWithdrawalController;
use App\Http\Controllers\Api\AnnouncementController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BidController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\CommentController;
use App\Http\Controllers\Api\Company\CompanyWholesaleProductController;
use App\Http\Controllers\Api\CompanyController;
use App\Http\Controllers\Api\ContactController;
use App\Http\Controllers\Api\FavoriteController;
use App\Http\Controllers\Api\FilterController;
use App\Http\Controllers\Api\HomeFeedController;
use App\Http\Controllers\Api\HomepageSectionsController;
use App\Http\Controllers\Api\MapsConfigController;
use App\Http\Controllers\Api\MapsGeocodeController;
use App\Http\Controllers\Api\ListingController;
use App\Http\Controllers\Api\ListingMapController;
use App\Http\Controllers\Api\ListingReportController;
use App\Http\Controllers\Api\MessageController;
use App\Http\Controllers\Api\MyListingsController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductShowController;
use App\Http\Controllers\Api\ProductSimilarController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\ProfileReportController;
use App\Http\Controllers\Api\PublicProfileController;
use App\Http\Controllers\Api\PurchaseController;
use App\Http\Controllers\Api\RegionController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\SavedSearchController;
use App\Http\Controllers\Api\SearchController;
use App\Http\Controllers\Api\SeoController;
use App\Http\Controllers\Api\UploadController;
use App\Http\Controllers\Api\Admin\AdminSeoController;
use App\Http\Controllers\Api\ServiceMarketController;
use App\Http\Controllers\Api\WholesaleMarketController;
use App\Http\Controllers\Api\WholesalePageSettingsController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    // Public
    Route::get('/maps/config', MapsConfigController::class);
    Route::middleware('throttle:60,1')->group(function () {
        Route::get('/maps/geocode/search', [MapsGeocodeController::class, 'search']);
        Route::get('/maps/geocode/reverse', [MapsGeocodeController::class, 'reverse']);
    });
    Route::get('/homepage/feed', HomeFeedController::class);
    Route::get('/homepage/sections', HomepageSectionsController::class);
    Route::get('/homepage/features', \App\Http\Controllers\Api\HomepageFeaturesController::class);
    Route::get('/listings', [ListingController::class, 'index']);
    Route::get('/listings/map', [ListingMapController::class, 'index']);
    Route::middleware(['optional.auth.api'])->group(function () {
        Route::get('/listings/{listing}', [ListingController::class, 'show']);
        Route::get('/listings/{listing}/reviews', [ReviewController::class, 'forListing']);
        Route::get('/products/{product}', ProductShowController::class);
        Route::post('/products/{product}/view', \App\Http\Controllers\Api\ProductViewController::class);
        Route::get('/products/{product}/similar', ProductSimilarController::class);
        Route::get('/products/{product}/comments', [CommentController::class, 'index']);
        Route::get('/products/{product}/bids', [BidController::class, 'index']);
        Route::get('/profile/by-id/{id}', [PublicProfileController::class, 'showById']);
        Route::get('/profile/by-id/{id}/listings', [PublicProfileController::class, 'listingsById']);
        Route::get('/profile/by-id/{id}/reviews', [PublicProfileController::class, 'reviewsById']);
        Route::get('/profile/{username}', [PublicProfileController::class, 'show']);
        Route::get('/profile/{username}/listings', [PublicProfileController::class, 'listings']);
        Route::get('/profile/{username}/reviews', [PublicProfileController::class, 'reviews']);
    });
    Route::get('/categories', [CategoryController::class, 'index']);
    Route::get('/categories/tree', [CategoryController::class, 'tree']);
    Route::get('/categories/by-slug/{slug}', [CategoryController::class, 'bySlug']);
    Route::get('/categories/{category}/subcategories', [CategoryController::class, 'subcategories']);
    Route::get('/seo/resolve', [SeoController::class, 'resolve']);
    Route::get('/categories/{category}/listing-schema', [\App\Http\Controllers\Api\ListingSchemaController::class, 'show']);
    Route::get('/regions', [RegionController::class, 'index']);
    Route::get('/areas', [RegionController::class, 'index']);
    Route::get('/regions/{region}/cities', [RegionController::class, 'cities']);
    Route::get('/companies', [CompanyController::class, 'index']);
    Route::get('/companies/{company}', [CompanyController::class, 'show'])->whereNumber('company');
    Route::get('/search', SearchController::class);
    Route::get('/filters', FilterController::class);
    Route::get('/contact/page', [\App\Http\Controllers\Api\ContactPageController::class, 'show']);
    Route::get('/cms/pages/{slug}', [\App\Http\Controllers\Api\CmsPageController::class, 'show']);
    Route::post('/contact', [ContactController::class, 'store']);
    Route::get('/announcements', [AnnouncementController::class, 'index']);
    Route::post('/visitors/track', [\App\Http\Controllers\Api\VisitorController::class, 'track']);
    Route::post('/listings/{listing}/report', [ListingReportController::class, 'store']);
    Route::middleware(['optional.auth.api'])->prefix('wholesale')->group(function () {
        Route::get('/page-settings', WholesalePageSettingsController::class);
        Route::get('/category-counts', [WholesaleMarketController::class, 'categoryCounts']);
        Route::get('/products', [WholesaleMarketController::class, 'index']);
        Route::get('/products/{product}', [WholesaleMarketController::class, 'show']);
        Route::get('/companies', [CompanyController::class, 'wholesaleCompanies']);
        Route::get('/companies/{company}', [CompanyController::class, 'wholesaleShow'])->whereNumber('company');
        Route::get('/companies/{company}/products', [CompanyController::class, 'wholesaleProducts'])->whereNumber('company');
    });
    Route::prefix('services')->group(function () {
        Route::get('/categories', [ServiceMarketController::class, 'categories']);
        Route::get('/providers', [ServiceMarketController::class, 'providers']);
        Route::get('/providers/{provider}', [ServiceMarketController::class, 'show'])->whereNumber('provider');
    });
    Route::get('/payment-methods', [\App\Http\Controllers\Api\Finance\PaymentConfigController::class, 'methods']);
    Route::get('/payment-methods/fields', [\App\Http\Controllers\Api\Finance\PaymentConfigController::class, 'fields']);
    Route::get('/finance/wallet/charge-schema', [\App\Http\Controllers\Api\Finance\WalletSchemaController::class, 'chargeSchema']);
    Route::get('/finance/wallet/withdraw-schema', [\App\Http\Controllers\Api\Finance\WalletSchemaController::class, 'withdrawSchema']);
    Route::get('/help/page', [\App\Http\Controllers\Api\HelpPageController::class, 'show']);
    Route::get('/branding', [BrandingController::class, 'show']);
    Route::get('/users/by-username/{username}', [ProfileController::class, 'showByUsername']);
    Route::get('/users/{user}', [ProfileController::class, 'show']);
    Route::post('/users/{user}/report', [ProfileReportController::class, 'store']);

    // Auth (public)
    Route::post('/auth/register', [AuthController::class, 'register']);
    Route::post('/auth/login', [AuthController::class, 'login']);
    Route::post('/auth/verify-email', [AuthController::class, 'verifyEmail']);
    Route::post('/auth/confirm-email', [AuthController::class, 'confirmEmail']);
    Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::get('/auth/password-policy', [AuthController::class, 'passwordPolicy']);

    // Auth (protected)
    Route::middleware('auth.api')->group(function () {
        Route::post('/upload', [UploadController::class, 'store']);
        Route::post('/auth/register/company', [AuthController::class, 'registerCompany']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/auth/user', [AuthController::class, 'user']);
        Route::post('/auth/presence', [AuthController::class, 'presence']);
        Route::post('/auth/presence/offline', [AuthController::class, 'presenceOffline']);
        Route::post('/auth/change-password', [AuthController::class, 'changePassword']);
        Route::post('/auth/change-email-request', [AuthController::class, 'changeEmailRequest']);
        Route::post('/auth/change-email-confirm', [AuthController::class, 'changeEmailConfirm']);
        Route::get('/companies/my-status', [CompanyController::class, 'myStatus']);
        Route::post('/wholesale/products/{product}/reserve', [WholesaleMarketController::class, 'reserve']);
        Route::delete('/wholesale/products/{product}/reserve', [WholesaleMarketController::class, 'cancelReservation']);
        Route::get('/wholesale/my-reservations', [WholesaleMarketController::class, 'myReservations']);
        Route::post('/wholesale/reservations/{reservation}/checkout', [PurchaseController::class, 'wholesaleCheckout']);
        Route::prefix('company/wholesale')->group(function () {
            Route::get('/products', [CompanyWholesaleProductController::class, 'index']);
            Route::post('/products', [CompanyWholesaleProductController::class, 'store']);
            Route::put('/products/{product}', [CompanyWholesaleProductController::class, 'update']);
            Route::delete('/products/{product}', [CompanyWholesaleProductController::class, 'destroy']);
            Route::post('/bulk-offers', [CompanyWholesaleProductController::class, 'storeBulkOffer']);
            Route::post('/products/bulk', [CompanyWholesaleProductController::class, 'storeBulkProducts']);
        });
        Route::prefix('services')->group(function () {
            Route::post('/providers', [ServiceMarketController::class, 'storeProvider']);
            Route::post('/requests', [ServiceMarketController::class, 'storeRequest']);
            Route::get('/my-requests', [ServiceMarketController::class, 'myRequests']);
            Route::get('/provider/dashboard', [ServiceMarketController::class, 'providerDashboard']);
            Route::patch('/requests/{serviceRequest}/status', [ServiceMarketController::class, 'updateRequestStatus']);
        });
        Route::middleware('can.create.listing')->group(function () {
            Route::post('/products', [ProductController::class, 'store']);
            Route::put('/products/{product}', [ProductController::class, 'update']);
            Route::post('/products/{product}/publish', [ProductController::class, 'publish']);
        });
        Route::get('/products', [ProductController::class, 'index']);
        Route::get('/favorites', [FavoriteController::class, 'index']);
        Route::post('/favorites/{product}', [FavoriteController::class, 'store']);
        Route::delete('/favorites/{product}', [FavoriteController::class, 'destroy']);
        Route::get('/saved-searches', [SavedSearchController::class, 'index']);
        Route::post('/saved-searches', [SavedSearchController::class, 'store']);
        Route::delete('/saved-searches/{savedSearch}', [SavedSearchController::class, 'destroy']);
        Route::get('/conversations', [MessageController::class, 'index']);
        Route::get('/conversations/{conversation}', [MessageController::class, 'show']);
        Route::post('/messages', [MessageController::class, 'store']);
        Route::post('/conversations/{conversation}/messages', [MessageController::class, 'reply']);
        Route::post('/products/{product}/bids', [BidController::class, 'store']);
        Route::get('/account/bids', [BidController::class, 'mine']);
        Route::get('/account/bids/incoming', [BidController::class, 'incoming']);
        Route::post('/products/{product}/bids/{bid}/accept', \App\Http\Controllers\Api\BidAcceptController::class);
        Route::post('/products/{product}/bids/{bid}/reject', [BidController::class, 'reject']);
        Route::delete('/products/{product}/bids/{bid}', [BidController::class, 'destroy']);
        Route::patch('/products/{product}/bids/{bid}/visibility', [BidController::class, 'toggleVisibility']);
        Route::post('/account/bids/{bid}/create-order', [BidController::class, 'createOrder']);
        Route::post('/products/{product}/view-request', [\App\Http\Controllers\Api\ViewRequestController::class, 'store']);
        Route::get('/account/view-requests', [\App\Http\Controllers\Api\ViewRequestController::class, 'indexMine']);
        Route::get('/account/view-requests/incoming', [\App\Http\Controllers\Api\ViewRequestController::class, 'indexIncoming']);
        Route::get('/products/{product}/view-requests', [\App\Http\Controllers\Api\ViewRequestController::class, 'indexForProduct']);
        Route::patch('/view-requests/{viewRequest}', [\App\Http\Controllers\Api\ViewRequestController::class, 'update']);
        Route::post('/products/{product}/comments', [CommentController::class, 'store']);
        // Legacy route (kept): like/dislike
        Route::post('/products/{product}/comments/{comment}/like', \App\Http\Controllers\Api\CommentLikeController::class);
        // Spec routes
        Route::put('/comments/{comment}', [CommentController::class, 'update']);
        Route::patch('/comments/{comment}/visibility', [CommentController::class, 'toggleVisibility']);
        Route::post('/comments/{comment}/like', \App\Http\Controllers\Api\CommentLikeController::class);
        Route::delete('/comments/{comment}', [CommentController::class, 'destroy']);
        Route::post('/products/{product}/bump', [ProductController::class, 'bump']);
        Route::delete('/products/{product}', [ProductController::class, 'destroy']);
        Route::post('/products/{product}/purchase', [PurchaseController::class, 'store']);
        Route::get('/products/{product}/checkout-payment-options', [\App\Http\Controllers\Api\Finance\CheckoutPaymentController::class, 'options']);
        Route::get('/seller/payout-profile', [\App\Http\Controllers\Api\Finance\SellerPayoutProfileController::class, 'show']);
        Route::put('/seller/payout-profile', [\App\Http\Controllers\Api\Finance\SellerPayoutProfileController::class, 'update']);
        Route::get('/seller/payment-setup-status', [\App\Http\Controllers\Api\Finance\SellerPayoutProfileController::class, 'setupStatus']);
        Route::get('/account/financial-requests', [\App\Http\Controllers\Api\Finance\WalletFinancialRequestController::class, 'index']);
        Route::post('/account/financial-requests/charge', [\App\Http\Controllers\Api\Finance\WalletFinancialRequestController::class, 'charge']);
        Route::post('/account/financial-requests/withdraw', [\App\Http\Controllers\Api\Finance\WalletFinancialRequestController::class, 'withdraw']);
        Route::get('/account/financial-activity', [\App\Http\Controllers\Api\Finance\FinancialActivityController::class, 'index']);
        Route::get('/notifications', [NotificationController::class, 'index']);
        Route::get('/notifications/{notification}', [NotificationController::class, 'show']);
        Route::post('/notifications/{notification}/read', [NotificationController::class, 'markAsRead']);
        Route::post('/notifications/read-all', [NotificationController::class, 'markAllAsRead']);
        Route::put('/profile', [ProfileController::class, 'update']);
        Route::post('/profile/avatar', [ProfileController::class, 'updateAvatar']);
        Route::post('/profile/cover', [ProfileController::class, 'updateCover']);
        Route::get('/users/{user}/reviews', [ReviewController::class, 'index']);
        Route::post('/reviews', [ReviewController::class, 'store']);
        Route::put('/reviews/{review}', [ReviewController::class, 'update']);
        Route::delete('/reviews/{review}', [ReviewController::class, 'destroy']);
        Route::post('/reviews/{review}/react', [ReviewController::class, 'react']);
        Route::get('/reviews/my', [ReviewController::class, 'myReviews']);
        Route::get('/reviews/given', [ReviewController::class, 'reviewsGiven']);

        // Account: verification, guarantee, balance, orders
        Route::post('/account/verify-document', [AccountController::class, 'verifyDocument']);
        Route::get('/account/verification-status', [AccountController::class, 'verificationStatus']);
        Route::post('/account/verify-absher', [AccountController::class, 'verifyAbsher']);
        Route::get('/account/guarantee-requests', [AccountController::class, 'guaranteeRequestsIndex']);
        Route::post('/account/guarantee-requests', [AccountController::class, 'guaranteeRequestsStore']);
        Route::get('/account/guarantee-status', [AccountController::class, 'guaranteeStatus']);
        Route::get('/account/listings', [ProductController::class, 'index']);
        Route::get('/account/balance', [AccountController::class, 'balance']);
        Route::get('/account/transactions', [AccountController::class, 'transactions']);
        Route::get('/account/reports', [AccountController::class, 'reports']);
        Route::post('/account/balance/charge', [AccountController::class, 'charge']);
        Route::get('/account/charge-requests', [AccountController::class, 'chargeRequests']);
        Route::post('/account/confirm-receipt', [AccountController::class, 'confirmReceipt']);
        Route::post('/account/withdraw', [AccountController::class, 'withdraw']);
        Route::get('/account/withdrawal-requests', [AccountController::class, 'withdrawalRequests']);
        Route::get('/account/stats', [AccountController::class, 'stats']);
        Route::get('/dashboard/home', [AccountController::class, 'dashboardHome']);
        Route::prefix('dashboard/listings')->group(function () {
            Route::get('/', [MyListingsController::class, 'index']);
            Route::patch('/{product}/status', [MyListingsController::class, 'toggleStatus']);
            Route::post('/{product}/bump', [MyListingsController::class, 'bump']);
            Route::delete('/{product}', [MyListingsController::class, 'destroy']);
            Route::patch('/{product}/mark-sold', [MyListingsController::class, 'markSold']);
            Route::post('/{product}/duplicate', [MyListingsController::class, 'duplicate']);
        });
        Route::get('/account/visitor-stats', [AccountController::class, 'visitorStats']);
        Route::post('/account/verify-company', [AccountController::class, 'verifyCompany']);
        Route::get('/account/orders', [OrderController::class, 'index']);
        Route::get('/account/orders/{order}', [OrderController::class, 'show']);
        Route::put('/account/orders/{order}', [OrderController::class, 'update']);
        Route::put('/account/orders/{order}/confirm', [OrderController::class, 'confirm']);
        Route::put('/account/orders/{order}/cancel', [OrderController::class, 'cancel']);
        Route::put('/account/orders/{order}/dispute', [OrderController::class, 'dispute']);
    });

    // Admin (protected, role: super_admin, admin, manager)
    Route::middleware(['auth.api', 'role:super_admin,admin,manager,employee,moderator,assistant'])->prefix('admin')->group(function () {
        Route::post('/comments/{comment}/reply', [CommentController::class, 'teamReply']);
        Route::get('/categories', [AdminCategoryController::class, 'index']);
        Route::post('/categories', [AdminCategoryController::class, 'store']);
        Route::put('/categories/{category}', [AdminCategoryController::class, 'update']);
        Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy']);
        Route::post('/categories/bulk-update', [AdminCategoryController::class, 'bulkUpdate']);
        Route::post('/categories/bulk-destroy', [AdminCategoryController::class, 'bulkDestroy']);
        Route::post('/categories/{category}/subcategories', [AdminCategoryController::class, 'storeSubcategory']);
        Route::put('/categories/{category}/subcategories/{subcategory}', [AdminCategoryController::class, 'updateSubcategory']);
        Route::delete('/categories/{category}/subcategories/{subcategory}', [AdminCategoryController::class, 'destroySubcategory']);
        Route::post('/categories/{category}/regions/{region}/toggle', [AdminCategoryController::class, 'toggleRegion']);
        Route::post('/categories/{category}/regions/{region}/wholesale', [AdminCategoryController::class, 'toggleWholesale']);
        Route::get('/orders', [AdminOrderController::class, 'index'])->middleware('permission:orders.view');
        Route::get('/orders/{purchase}', [AdminOrderController::class, 'show'])->middleware('permission:orders.view');
        Route::get('/bids', [AdminBidController::class, 'index'])->middleware(['role:super_admin,admin', 'permission:bids.admin_view']);
        Route::get('/bids/{bid}', [AdminBidController::class, 'show'])->middleware(['role:super_admin,admin', 'permission:bids.admin_view']);
        Route::patch('/bids/{bid}/hide', [AdminBidController::class, 'hide'])->middleware(['role:super_admin,admin', 'permission:bids.admin_manage']);
        Route::delete('/bids/{bid}', [AdminBidController::class, 'destroy'])->middleware(['role:super_admin,admin', 'permission:bids.admin_manage']);
        Route::put('/orders/{purchase}', [AdminOrderController::class, 'update'])->middleware('permission:orders.update_status');
        Route::post('/orders/{purchase}/cancel', [AdminOrderController::class, 'cancel'])->middleware('permission:orders.update_status');
        Route::post('/orders/{purchase}/force-complete', [AdminOrderController::class, 'forceComplete'])->middleware('permission:orders.dispute_resolve');
        Route::post('/orders/{purchase}/force-refund', [AdminOrderController::class, 'forceRefund'])->middleware('permission:orders.refund');
        Route::get('/withdrawal-requests', [AdminWithdrawalController::class, 'index'])->middleware('permission:finance.approve_withdrawal');
        Route::post('/withdrawal-requests/{withdrawal_request}/approve', [AdminWithdrawalController::class, 'approve'])->middleware('permission:finance.approve_withdrawal');
        Route::post('/withdrawal-requests/{withdrawal_request}/reject', [AdminWithdrawalController::class, 'reject'])->middleware('permission:finance.approve_withdrawal');
        Route::get('/finance/payment-methods', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'index'])->middleware('permission:settings.update');
        Route::post('/finance/payment-methods', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'store'])->middleware('permission:settings.update');
        Route::put('/finance/payment-methods/{paymentMethod}', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'update'])->middleware('permission:settings.update');
        Route::post('/finance/payment-method-fields/reorder', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'reorderFields'])->middleware('permission:settings.update');
        Route::post('/finance/payment-methods/{paymentMethod}/fields', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'storeField'])->middleware('permission:settings.update');
        Route::put('/finance/payment-method-fields/{field}', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'updateField'])->middleware('permission:settings.update');
        Route::delete('/finance/payment-method-fields/{field}', [\App\Http\Controllers\Api\Admin\AdminPaymentMethodController::class, 'destroyField'])->middleware('permission:settings.update');
        Route::get('/finance/requests', [\App\Http\Controllers\Api\Admin\AdminFinancialRequestController::class, 'index'])->middleware('permission:finance.approve_charge');
        Route::get('/finance/requests/{financialRequest}', [\App\Http\Controllers\Api\Admin\AdminFinancialRequestController::class, 'show'])->middleware('permission:finance.approve_charge');
        Route::post('/finance/requests/{financialRequest}/approve', [\App\Http\Controllers\Api\Admin\AdminFinancialRequestController::class, 'approve'])->middleware('permission:finance.approve_charge');
        Route::post('/finance/requests/{financialRequest}/reject', [\App\Http\Controllers\Api\Admin\AdminFinancialRequestController::class, 'reject'])->middleware('permission:finance.approve_charge');
        Route::get('/finance/order-payments', [\App\Http\Controllers\Api\Admin\AdminOrderPaymentRequestController::class, 'index'])->middleware('permission:finance.approve_charge');
        Route::post('/finance/order-payments/{orderPaymentRequest}/approve', [\App\Http\Controllers\Api\Admin\AdminOrderPaymentRequestController::class, 'approve'])->middleware('permission:finance.approve_charge');
        Route::post('/finance/order-payments/{orderPaymentRequest}/reject', [\App\Http\Controllers\Api\Admin\AdminOrderPaymentRequestController::class, 'reject'])->middleware('permission:finance.approve_charge');
        Route::get('/finance/payout-profiles', [\App\Http\Controllers\Api\Admin\AdminSellerPayoutProfileController::class, 'index'])->middleware('permission:finance.approve_charge');
        Route::post('/finance/payout-profiles/{sellerPayoutProfile}/verify', [\App\Http\Controllers\Api\Admin\AdminSellerPayoutProfileController::class, 'verify'])->middleware('permission:finance.approve_charge');
        Route::post('/finance/payout-profiles/{sellerPayoutProfile}/reject', [\App\Http\Controllers\Api\Admin\AdminSellerPayoutProfileController::class, 'reject'])->middleware('permission:finance.approve_charge');
        Route::get('/finance/cod-policies', [\App\Http\Controllers\Api\Admin\AdminCodPolicyController::class, 'index'])->middleware('permission:settings.update');
        Route::post('/finance/cod-policies', [\App\Http\Controllers\Api\Admin\AdminCodPolicyController::class, 'store'])->middleware('permission:settings.update');
        Route::put('/finance/cod-policies/{codPolicy}', [\App\Http\Controllers\Api\Admin\AdminCodPolicyController::class, 'update'])->middleware('permission:settings.update');
        Route::delete('/finance/cod-policies/{codPolicy}', [\App\Http\Controllers\Api\Admin\AdminCodPolicyController::class, 'destroy'])->middleware('permission:settings.update');
        Route::get('/category-fields', [\App\Http\Controllers\Api\Admin\AdminCategoryFieldController::class, 'index'])->middleware('permission:settings.update');
        Route::post('/category-fields', [\App\Http\Controllers\Api\Admin\AdminCategoryFieldController::class, 'store'])->middleware('permission:settings.update');
        Route::put('/category-fields/{categoryField}', [\App\Http\Controllers\Api\Admin\AdminCategoryFieldController::class, 'update'])->middleware('permission:settings.update');
        Route::delete('/category-fields/{categoryField}', [\App\Http\Controllers\Api\Admin\AdminCategoryFieldController::class, 'destroy'])->middleware('permission:settings.update');
        Route::get('/category-schemas', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'index'])->middleware('permission:settings.update');
        Route::post('/category-schemas', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'store'])->middleware('permission:settings.update');
        Route::get('/category-schemas/{categorySchema}', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'show'])->middleware('permission:settings.update');
        Route::put('/category-schemas/{categorySchema}', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'update'])->middleware('permission:settings.update');
        Route::post('/category-schemas/{categorySchema}/publish', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'publish'])->middleware('permission:settings.update');
        Route::post('/category-schemas/{categorySchema}/clone', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'clone'])->middleware('permission:settings.update');
        Route::put('/category-schemas/{categorySchema}/reorder', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'reorder'])->middleware('permission:settings.update');
        Route::post('/category-schemas/{categorySchema}/sections/{section}/duplicate', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'duplicateSection'])->middleware('permission:settings.update');
        Route::post('/category-schemas/{categorySchema}/sections', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'storeSection'])->middleware('permission:settings.update');
        Route::post('/category-schemas/{categorySchema}/fields', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'storeField'])->middleware('permission:settings.update');
        Route::put('/category-schema-fields/{categorySchemaField}', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'updateField'])->middleware('permission:settings.update');
        Route::delete('/category-schema-fields/{categorySchemaField}', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'destroyField'])->middleware('permission:settings.update');
        Route::put('/category-schemas/{categorySchema}/policy', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'updatePolicy'])->middleware('permission:settings.update');
        Route::post('/category-schemas/{categorySchema}/agreements', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'storeAgreement'])->middleware('permission:settings.update');
        Route::delete('/listing-agreements/{listingAgreement}', [\App\Http\Controllers\Api\Admin\AdminCategorySchemaController::class, 'destroyAgreement'])->middleware('permission:settings.update');
        Route::get('/charge-requests', [AdminChargeRequestController::class, 'index'])->middleware('permission:finance.approve_charge');
        Route::post('/charge-requests/{charge_request}/approve', [AdminChargeRequestController::class, 'approve'])->middleware('permission:finance.approve_charge');
        Route::post('/charge-requests/{charge_request}/reject', [AdminChargeRequestController::class, 'reject'])->middleware('permission:finance.approve_charge');
        Route::get('/guarantee-requests', [AdminGuaranteeRequestController::class, 'index'])->middleware('permission:compliance.review_guarantee_requests');
        Route::post('/guarantee-requests/{guarantee_request}/approve', [AdminGuaranteeRequestController::class, 'approve'])->middleware('permission:compliance.review_guarantee_requests');
        Route::post('/guarantee-requests/{guarantee_request}/reject', [AdminGuaranteeRequestController::class, 'reject'])->middleware('permission:compliance.review_guarantee_requests');
        Route::get('/users', [AdminUserController::class, 'index']);
        Route::post('/users', [AdminUserController::class, 'store'])->middleware('permission:users.assign_roles');
        Route::get('/users/{user}', [AdminUserController::class, 'show']);
        Route::put('/users/{user}', [AdminUserController::class, 'update']);
        Route::get('/products', [AdminProductController::class, 'index']);
        Route::get('/products/{product}', [AdminProductController::class, 'show']);
        Route::put('/products/{product}', [AdminProductController::class, 'update']);
        Route::delete('/products/{product}', [AdminProductController::class, 'destroy']);
        Route::get('/regions', [AdminRegionController::class, 'index']);
        Route::post('/regions', [AdminRegionController::class, 'store']);
        Route::put('/regions/{region}', [AdminRegionController::class, 'update']);
        Route::delete('/regions/{region}', [AdminRegionController::class, 'destroy']);
        Route::post('/regions/bulk-update', [AdminRegionController::class, 'bulkUpdate']);
        Route::post('/regions/bulk-destroy', [AdminRegionController::class, 'bulkDestroy']);
        Route::post('/regions/{region}/cities', [AdminRegionController::class, 'storeCity']);
        Route::put('/regions/{region}/cities/{city}', [AdminRegionController::class, 'updateCity']);
        Route::delete('/regions/{region}/cities/{city}', [AdminRegionController::class, 'destroyCity']);
        Route::get('/permissions', [AdminPermissionController::class, 'index']);
        Route::get('/permissions/roles', [AdminPermissionController::class, 'roles']);
        Route::get('/permissions/roles/{role}', [AdminPermissionController::class, 'rolePermissions']);
        Route::put('/permissions/roles/{role}', [AdminPermissionController::class, 'syncRole'])
            ->middleware('permission:users.assign_roles');
        Route::get('/assistants/meta', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'meta'])
            ->middleware('permission:assistants.manage');
        Route::get('/assistants', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'index'])
            ->middleware('permission:assistants.manage');
        Route::post('/assistants', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'store'])
            ->middleware('permission:assistants.manage');
        Route::get('/assistants/{assistant}', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'show'])
            ->middleware('permission:assistants.manage');
        Route::put('/assistants/{assistant}', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'update'])
            ->middleware('permission:assistants.manage');
        Route::delete('/assistants/{assistant}', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'destroy'])
            ->middleware('permission:assistants.manage');
        Route::post('/assistants/{assistant}/reset-password', [\App\Http\Controllers\Api\Admin\AdminAssistantController::class, 'resetPassword'])
            ->middleware('permission:assistants.manage');
        Route::get('/tasks', [AdminTaskController::class, 'index'])->middleware('permission:tasks.view');
        Route::post('/tasks', [AdminTaskController::class, 'store'])->middleware('permission:tasks.create');
        Route::put('/tasks/{task}', [AdminTaskController::class, 'update'])->middleware('permission:tasks.update');
        Route::delete('/tasks/{task}', [AdminTaskController::class, 'destroy'])->middleware('permission:tasks.close');
        Route::get('/tasks/assignees', [AdminTaskController::class, 'assignees'])->middleware('permission:tasks.assign');
        Route::get('/contact-inquiries', [AdminContactInquiryController::class, 'index']);
        Route::get('/contact-inquiries/assignees', [AdminContactInquiryController::class, 'assignees']);
        Route::get('/contact-inquiries/{contact_inquiry}', [AdminContactInquiryController::class, 'show']);
        Route::put('/contact-inquiries/{contact_inquiry}', [AdminContactInquiryController::class, 'update']);
        Route::get('/listing-reports', [AdminListingReportController::class, 'index']);
        Route::get('/listing-reports/assignees', [AdminListingReportController::class, 'assignees']);
        Route::get('/listing-reports/{listing_report}', [AdminListingReportController::class, 'show']);
        Route::put('/listing-reports/{listing_report}', [AdminListingReportController::class, 'update']);
        Route::get('/profile-reports', [AdminProfileReportController::class, 'index']);
        Route::get('/profile-reports/assignees', [AdminProfileReportController::class, 'assignees']);
        Route::get('/profile-reports/{profile_report}', [AdminProfileReportController::class, 'show']);
        Route::put('/profile-reports/{profile_report}', [AdminProfileReportController::class, 'update']);
        Route::get('/announcements', [AdminAnnouncementController::class, 'index']);
        Route::post('/announcements', [AdminAnnouncementController::class, 'store']);
        Route::put('/announcements/{admin_announcement}', [AdminAnnouncementController::class, 'update']);
        Route::delete('/announcements/{admin_announcement}', [AdminAnnouncementController::class, 'destroy']);
        Route::get('/conversations', [AdminMessageController::class, 'index']);
        Route::get('/messages/summary', [AdminMessageController::class, 'unifiedSummary']);
        Route::get('/conversations/{conversation}', [AdminMessageController::class, 'show']);
        Route::post('/conversations/{conversation}/messages', [AdminMessageController::class, 'reply']);
        Route::post('/messages/direct', [AdminMessageController::class, 'directMessage']);
        Route::post('/messages/open-direct-conversation', [AdminMessageController::class, 'openDirectConversation']);
        Route::post('/messages/open-product-conversation', [AdminMessageController::class, 'openProductConversation']);
        Route::get('/visitors', [AdminVisitorController::class, 'index']);
        Route::post('/users/{user}/ban', [AdminUserController::class, 'ban']);
        Route::post('/users/{user}/unban', [AdminUserController::class, 'unban']);
        Route::post('/users/{user}/suspend', [AdminUserController::class, 'suspend']);
        Route::post('/users/{user}/unsuspend', [AdminUserController::class, 'unsuspend']);
        Route::post('/users/{user}/verify', [AdminUserController::class, 'verify']);
        Route::post('/users/{user}/refund-guarantee', [AdminUserController::class, 'refundGuarantee']);
        Route::post('/users/{user}/deduct-guarantee', [AdminUserController::class, 'deductGuarantee']);
        Route::get('/companies', [AdminCompanyVerificationController::class, 'index']);
        Route::post('/companies/{company}/approve', [AdminCompanyVerificationController::class, 'approve']);
        Route::post('/companies/{company}/reject', [AdminCompanyVerificationController::class, 'reject']);
        Route::post('/users/{user}/credit-balance', [AdminUserController::class, 'creditBalance'])
            ->middleware('permission:finance.credit_balance');
        Route::post('/products/{product}/approve', [AdminProductController::class, 'approve']);
        Route::post('/products/{product}/reject', [AdminProductController::class, 'reject']);
        Route::get('/analytics', AdminAnalyticsController::class);
        Route::get('/analytics/regions', [AdminAnalyticsController::class, 'regions']);
        Route::get('/overview', AdminOverviewController::class);
        Route::get('/audit-logs', [AdminAuditController::class, 'index']);
        Route::get('/verifications', [AdminVerificationController::class, 'index'])->middleware('permission:compliance.review_document_verifications');
        Route::post('/verifications/{document_verification}/approve', [AdminVerificationController::class, 'approve'])->middleware('permission:compliance.review_document_verifications');
        Route::post('/verifications/{document_verification}/reject', [AdminVerificationController::class, 'reject'])->middleware('permission:compliance.review_document_verifications');
        Route::get('/security/password-policy', [AdminSecuritySettingsController::class, 'showPasswordPolicy']);
        Route::put('/security/password-policy', [AdminSecuritySettingsController::class, 'updatePasswordPolicy']);
        Route::get('/settings', [AdminSettingsController::class, 'index'])->middleware('permission:settings.view');
        Route::put('/settings/security', [AdminSettingsController::class, 'updateSecurity'])->middleware('permission:settings.update');
        Route::put('/settings/account', [AdminSettingsController::class, 'updateAccount'])->middleware('permission:settings.update');
        Route::put('/settings/auth', [AdminSettingsController::class, 'updateAuth'])->middleware('permission:settings.update');
        Route::put('/settings/content', [AdminSettingsController::class, 'updateContent'])->middleware('permission:settings.update');
        Route::put('/settings/wholesale-market-page', [AdminSettingsController::class, 'updateWholesaleMarketPage'])->middleware('permission:settings.update');
        Route::put('/settings/payments', [AdminSettingsController::class, 'updatePayments'])->middleware('permission:settings.update');
        Route::put('/settings/contact', [AdminSettingsController::class, 'updateContact'])->middleware('permission:settings.update');
        Route::get('/branding', [AdminBrandingController::class, 'show'])->middleware('permission:settings.view');
        Route::put('/branding', [AdminBrandingController::class, 'update'])->middleware('permission:settings.update');
        Route::post('/branding/upload', [AdminBrandingController::class, 'upload'])->middleware('permission:settings.update');
        Route::middleware('permission:seo.manage')->prefix('seo')->group(function () {
            Route::get('/dashboard', [AdminSeoController::class, 'dashboard']);
            Route::get('/global', [AdminSeoController::class, 'globalShow']);
            Route::put('/global', [AdminSeoController::class, 'globalUpdate']);
            Route::get('/pages', [AdminSeoController::class, 'pagesIndex']);
            Route::post('/pages', [AdminSeoController::class, 'pagesStore']);
            Route::put('/pages/{pageKey}', [AdminSeoController::class, 'pagesUpdate']);
            Route::delete('/pages/{pageKey}', [AdminSeoController::class, 'pagesDestroy']);
            Route::post('/pages/bulk', [AdminSeoController::class, 'pagesBulk']);
            Route::post('/pages/sync-categories', [AdminSeoController::class, 'syncCategories']);
            Route::get('/sitemap', [AdminSeoController::class, 'sitemapShow']);
            Route::put('/sitemap', [AdminSeoController::class, 'sitemapUpdate']);
            Route::post('/sitemap/generate', [AdminSeoController::class, 'sitemapGenerate']);
            Route::get('/robots', [AdminSeoController::class, 'robotsShow']);
            Route::put('/robots', [AdminSeoController::class, 'robotsUpdate']);
            Route::get('/audit', [AdminSeoController::class, 'auditIssues']);
            Route::post('/audit/run', [AdminSeoController::class, 'runAudit']);
            Route::post('/cache/clear', [AdminSeoController::class, 'clearCache']);
            Route::post('/upload/og-image', [AdminSeoController::class, 'uploadOgImage']);
        });
        Route::get('/help/support-settings', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'getSupportSettings'])->middleware('permission:settings.update');
        Route::put('/help/support-settings', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'updateSupportSettings'])->middleware('permission:settings.update');
        Route::get('/help/blocks', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'indexBlocks'])->middleware('permission:settings.update');
        Route::post('/help/blocks', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'storeBlock'])->middleware('permission:settings.update');
        Route::put('/help/blocks/{helpBlock}', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'updateBlock'])->middleware('permission:settings.update');
        Route::post('/help/blocks/reorder', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'reorderBlocks'])->middleware('permission:settings.update');
        Route::get('/help/categories', [\App\Http\Controllers\Api\Admin\AdminHelpController::class, 'indexCategories'])->middleware('permission:settings.update');
        Route::get('/order-edit-policies', [\App\Http\Controllers\Api\Admin\AdminOrderEditPolicyController::class, 'show'])->middleware('permission:settings.update');
        Route::put('/order-edit-policies', [\App\Http\Controllers\Api\Admin\AdminOrderEditPolicyController::class, 'update'])->middleware('permission:settings.update');
        Route::get('/cms/pages', [\App\Http\Controllers\Api\Admin\AdminCmsPageController::class, 'index'])->middleware('permission:settings.update');
        Route::post('/cms/pages', [\App\Http\Controllers\Api\Admin\AdminCmsPageController::class, 'store'])->middleware('permission:settings.update');
        Route::put('/cms/pages/{cmsPage}', [\App\Http\Controllers\Api\Admin\AdminCmsPageController::class, 'update'])->middleware('permission:settings.update');
        Route::get('/settings/mail', [\App\Http\Controllers\Api\Admin\AdminMailSettingsController::class, 'show'])->middleware('permission:settings.view');
        Route::put('/settings/mail', [\App\Http\Controllers\Api\Admin\AdminMailSettingsController::class, 'update'])->middleware('permission:settings.update');
        Route::post('/settings/mail/test', [\App\Http\Controllers\Api\Admin\AdminMailSettingsController::class, 'sendTest'])->middleware('permission:settings.update');
    });
});

// Backward-compatible public profile endpoints without v1 prefix.
Route::middleware(['optional.auth.api'])->group(function () {
    Route::get('/profile/{username}', [PublicProfileController::class, 'show']);
    Route::get('/profile/{username}/listings', [PublicProfileController::class, 'listings']);
    Route::get('/profile/{username}/reviews', [PublicProfileController::class, 'reviews']);
});
