/** Common Lucide icon names for admin pickers (categories, listing schema features). */
export const LUCIDE_ICON_OPTIONS = [
  "Package",
  "Home",
  "Car",
  "Building2",
  "TreeDeciduous",
  "Wifi",
  "Zap",
  "Droplets",
  "ChefHat",
  "Wind",
  "Shield",
  "Elevator",
  "Waves",
  "Flower2",
  "ParkingCircle",
  "MapPin",
  "Bed",
  "Bath",
  "Ruler",
  "Landmark",
  "Store",
  "Truck",
  "Star",
  "Heart",
  "Search",
]
